In [ ]:
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, mean_squared_log_error
from datetime import datetime

In [ ]:
# import driv

from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/cleaned_df.csv")

In [ ]:
df = pd.get_dummies(df, columns=['PromoInterval'])

In [ ]:
# defining dependent variable
dependent_variables = 'Sales'

# defining independent variable
independent_variables = list(df.columns.drop(['Promo2SinceYear','Date','Sales']))

In [ ]:
#List of Independent Variable
independent_variables

['Store',
 'DayOfWeek',
 'Customers',
 'Open',
 'Promo',
 'StateHoliday',
 'SchoolHoliday',
 'StoreType',
 'Assortment',
 'CompetitionDistance',
 'CompetitionOpenSinceMonth',
 'CompetitionOpenSinceYear',
 'Promo2',
 'Promo2SinceWeek',
 'PromoInterval_0',
 'PromoInterval_Feb,May,Aug,Nov',
 'PromoInterval_Jan,Apr,Jul,Oct',
 'PromoInterval_Mar,Jun,Sept,Dec']

In [ ]:
# Create the data of independent variables
X = df[independent_variables].values

# Create the data of dependent variable
y = df[dependent_variables].values

In [ ]:

# splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)
print(X_train.shape)
print(X_test.shape)

(813767, 18)
(203442, 18)


In [ ]:
# Here we Train the model
reg = LinearRegression().fit(X_train, y_train)

In [ ]:
#Checking the Regression Score i.e R-squared value
reg.score(X_train, y_train)

0.8679206697324997

In [ ]:
# Checking the cofficient of different independent columns
reg.coef_

array([-1.32661173e-01, -6.87369785e+01,  6.29850239e+00,  1.38112319e+03,
        1.24770167e+03, -3.76782513e+02,  4.87962432e+01,  2.24825342e+02,
        1.87661162e+02,  2.41828369e-02,  2.73113453e+01,  7.05411500e-02,
       -3.97995013e+01,  1.04348779e+01,  3.97995013e+01,  2.59182960e+01,
        1.13149518e+02, -1.78867315e+02])

In [ ]:
reg.intercept_

-454.0184460296705

In [ ]:
#Predicting Dependent Variable With Test Dataset i.e 20%
y_pred = reg.predict(X_test)
y_pred

array([ 7042.92406502, 12597.30829286,  9190.46998935, ...,
        6963.41639908,  5964.7289964 ,  3956.46402394])

In [ ]:
# Original Test Dependent Value
y_test

array([7285, 6221, 8132, ..., 6191, 5663, 2698])

In [ ]:
#Predicting on Train Dataset
y_pred_train = reg.predict(X_train)
y_pred_train


array([6032.57725724,  489.64293356, 4448.39252875, ..., 7331.14268431,
       3131.38510076, 5525.62983862])

In [ ]:
# Dependent Variable With Train Dataset i.e 80 %
y_train

array([6394,    0, 5369, ..., 7404, 2864, 5541])

In [ ]:
#Calculate MSE & RMSE for Test Prediction
MSE  = mean_squared_error(y_test, y_pred)
print("MSE :" , MSE)

RMSE = np.sqrt(MSE)
print("RMSE :" ,RMSE)

MSE : 1942272.1973863924
RMSE : 1393.6542603480939


In [ ]:
r2 = r2_score(y_test, y_pred)
print("R2 :" ,r2)

R2 : 0.8685587843488419
